names = [
    "Tad Whistle",
    "Brick Leatherberry",
    "Storm Thompson",
    "Rita Breaker",
    "Rocky Clover",
    "Jacky Guess",
    "Ernest Neighbour",
    "Dewey Forte: Grippli Spy",
    "Terri-Mae Rocket",
    "Sam \"Eight-Ball\" Bowling",
    "\"Dandy\" Sam Pepper",
    "Dwayne Ocean",
    "McInnen Dust",
    "Dr. Backspace",
    "Maury Dunst-Rhino",
    "Scotch Mercedes",
    "Percival Mayonnaise",
    "Rip Cleaver",
    "Axel Petty",
    "\"Pinch\" Honeydew",
    "\"Fancy\" Nancy Cuttglass",
    "Bucket Dorshan",
    "Basil Weed II",
    "Timothy G. Raspberry",
    "Apple-May Peppercorn",
    "\"Surf\" Randy McIntosh",
    "Jayden Naiden-Skylar",
    "Doug Lighteningbug",
    "Rufus Penchant",
    "Teddy Bullcrest",
    "Teaky Sales",
    "Ruby Lust",
    "Janice Chestnut",
    "Grey Grindley",
    "Tanner Oblong",
    "Linus Snackbar",
    "Vicky Coxwell",
    "Rolf Popp",
    "Finn Richlore",
    "Wilbur Chestnut",
    "Jenny Belong",
    "Lottie T. Goodword",
    "Arsen Fuisz",
    "Jack Formerwolf",
    "Helmut Snoregas"
]